# Generated by Django 4.2.1 on 2023-06-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model_work_place',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('computer_type', models.CharField(max_length=50)),
                ('monitor_size', models.CharField(max_length=50)),
                ('storage_type', models.CharField(max_length=50)),
                ('hdd_memory_size', models.CharField(max_length=50)),
                ('ssd_memory_size', models.CharField(max_length=50)),
                ('processor_type', models.CharField(max_length=50)),
                ('processor_note', models.TextField()),
                ('graphics_card', models.CharField(max_length=100)),
                ('keyboard', models.CharField(max_length=100)),
                ('mouse', models.CharField(max_length=100)),
                ('letters', models.TextField()),
                ('current_date', models.DateField()),
                ('desired_date', models.DateField()),
                ('ups_needed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'work_place',
            },
        ),
    ]
